config/routes.rb
Mydemo::Application.routes.draw do
  resources :demos

  root 'welcome#index'
  get "welcome/index"
  get "welcome/index2"
  get "welcome/index3"

  

end

app/models/demo.rb
class Demo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :set_demo, only: [:show, :edit, :update, :destroy]

  # GET /demos
  # GET /demos.json
  def index
    @demos = Demo.all
  end

  # GET /demos/1
  # GET /demos/1.json
  def show
  end

  # GET /demos/new
  def new
    @demo = Demo.new
  end

  # GET /demos/1/edit
  def edit
  end

  # POST /demos
  # POST /demos.json
  def create
    @demo = Demo.new(demo_params)

    respond_to do |format|
      if @demo.save
        format.html { redirect_to @demo, notice: 'Demo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @demo }
      else
        format.html { render action: 'new' }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /demos/1
  # PATCH/PUT /demos/1.json
  def update
    respond_to do |format|
      if @demo.update(demo_params)
        format.html { redirect_to @demo, notice: 'Demo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demos/1
  # DELETE /demos/1.json
  def destroy
    @demo.destroy
    respond_to do |format|
      format.html { redirect_to demos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_demo
      @demo = Demo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def demo_params
      params.require(:demo).permit(:author, :title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/demos_helper.rb
module DemosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/demos/_form.html.erb
<%= form_for(@demo) do |f| %>
  <% if @demo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demo.errors.count, "error") %> prohibited this demo from being saved:</h2>

      <ul>
      <% @demo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/demos/edit.html.erb
<h1>Editing demo</h1>

<%= render 'form' %>

<%= link_to 'Show', @demo %> |
<%= link_to 'Back', demos_path %>

app/views/demos/index.html.erb
<h1>Listing demos</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @demos.each do |demo| %>
      <tr>
        <td><%= demo.author %></td>
        <td><%= demo.title %></td>
        <td><%= demo.description %></td>
        <td><%= link_to 'Show', demo %></td>
        <td><%= link_to 'Edit', edit_demo_path(demo) %></td>
        <td><%= link_to 'Destroy', demo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Demo', new_demo_path %>

app/views/demos/new.html.erb
<h1>New demo</h1>

<%= render 'form' %>

<%= link_to 'Back', demos_path %>

app/views/demos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @demo.author %>
</p>

<p>
  <strong>Title:</strong>
  <%= @demo.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @demo.description %>
</p>

<%= link_to 'Edit', edit_demo_path(@demo) %> |
<%= link_to 'Back', demos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
  <title>Mydemo</title>
  <link rel="stylesheet" type="text/css" href="/assets/normalize.css" />
  <link rel="stylesheet" type="text/css" href="/assets/mystyle.css" />
  <link rel="stylesheet" type="text/css" href="/assets/font-awesome.min.css" />
  <script src="/assets/modernizr-2.6.2.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= yield %>

	<div class="component">
		<!-- Start Nav Structure -->
		<button class="cn-button" id="cn-button">+</button>
		<div class="cn-wrapper" id="cn-wrapper">
		    <ul>
		      <li>
		      	<a href="/welcome/index">
		      		<span class="icon-picture"><i class="fa fa-home fa-fw"></i></span>
		      	</a>
		      </li>
		      <li>
		      	<a href="/welcome/index2"><span class="icon-headphones"><i class="fa fa-flag"></i></span></a>
		      </li>
		      <li>
		      	<a href="/welcome/index3"><span class="icon-home"><i class="fa fa-life-ring"></i></span></a>
		      </li>
		      <li>
		      	<a href="#"><span class="icon-facetime-video"><i class="fa fa-envelope"></i></span></a>
		      </li>
		      <li>
		      	<a href="#"><span class="icon-envelope-alt"><i class="fa fa-fighter-jet"></i></span></a>
		      </li>
		    </ul>
		</div>
		<div id="cn-overlay" class="cn-overlay"></div>
		<!-- End Nav Structure -->
	</div>  
	<script src="/assets/ripple.js"></script>
	<script src="/assets/mydemo.js" data-turbolinks-track="true"></script>
	<script src="/assets/polyfills.js"></script>
</body>
</html>

app/views/welcome/index.html.erb
<div class="my-hearts">
	<i class="fa fa-heart-o fa-3x"></i>
	<i class="fa fa-heart-o fa-5x"></i>
	<i class="fa fa-heart-o fa-3x"></i>
	<i class="fa fa-heart-o fa-5x"></i>
	<i class="fa fa-heart-o fa-3x"></i>
	<i class="fa fa-heart-o fa-5x"></i>
	<i class="fa fa-heart-o fa-3x"></i>
	<i class="fa fa-heart-o fa-5x"></i>
	<i class="fa fa-heart-o fa-3x"></i>
</div>

<link rel="stylesheet" type="text/css" href="/assets/demo1/component1.css" />

    <div class="content">
      <ul class="grid cs-style-1 float-lt">
				<li>
					<figure>
						<img src="../images/1.png" alt="img01">
						<figcaption>
							<h3>photo</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1115960-Music">Take a look</a>
						</figcaption>
					</figure>
				</li>
			</ul>
      <ul class="grid cs-style-2 float-rt">
				<li>
					<figure>
						<img src="../images/2.png" alt="img02">
						<figcaption>
							<h3>Photo</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1115960-Music">Take a look</a>
						</figcaption>
					</figure>
				</li>
			</ul>
			<ul class="grid cs-style-3 float-lt">
				<li>
					<figure>
						<img src="../images/3.png" alt="img03">
						<figcaption>
							<h3>Phone</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1115960-Music">Take a look</a>
						</figcaption>
					</figure>
				</li>
			</ul>
			<ul class="grid cs-style-4 float-rt">
				<li>
					<figure>
						<img src="../images/4.png" alt="img04">
						<figcaption>
							<h3>Setting</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1115960-Music">Take a look</a>
						</figcaption>
					</figure>
				</li>
			</ul>
			<ul class="grid cs-style-5 float-lt">
				<li>
					<figure>
						<img src="../images/5.png" alt="img05">
						<figcaption>
							<h3>Map</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1115960-Music">Take a look</a>
						</figcaption>
					</figure>
				</li>
			</ul>
			<ul class="grid cs-style-7 float-rt">
				<li>
					<figure>
						<img src="../images/6.png" alt="img06">
						<figcaption>
							<h3>Game</h3>
							<span>Jacob Cummings</span>
							<a href="http://dribbble.com/shots/1115960-Music">Take a look</a>
						</figcaption>
					</figure>
				</li>
			</ul>
			
		</div><!-- /container -->
<script src="/assets/demo1/toucheffects.js"></script>

app/views/welcome/index2.html.erb
<link rel="stylesheet" type="text/css" href="/assets/demo2/demo2.css">
<div class="ta">
    <textarea spellcheck="false" class="textarea"></textarea>
</div>

<script src="http://yandex.st/highlightjs/8.0/highlight.min.js"></script>
<script src="/assets/jquery.js"></script>
<script type="text/javascript" src="/assets/demo2/jquery.typetype.min.js"></script>
<script type="text/javascript">
$(function(){

  hljs.configure({languages:['js']})

  $('.textarea').focus()
    .typetype("改变，永远不嫌晚!", {
      callback: function() {
        $('body').addClass('reveal')
      }
    }).delay(1500)
    .typetype("\n\n无论你是几岁，也无论你目前所处的境况有多糟...").delay(1500)
    .typetype("\n\n只要立定目标、一步一步往前走，人生随时都有翻盘的可能性!")

})
</script>


app/views/welcome/index3.html.erb
<script src="/assets/jquery.js"></script>
<script src="/assets/jcarousellite_1.0.1.min.js"></script>
  <div id="container" class="mycenter">
    <ul id="indexAdList">
      <li>
      	<i class="fa fa-heart-o"></i>
      </li>
      <li>
      	<i class="fa fa-heart-o fa-2x"></i>
      </li>
      <li>
      	<i class="fa fa-heart-o fa-3x"></i>
      </li>
      <li>
      	<i class="fa fa-heart-o fa-4x"></i>
      </li>
      <li>
      	<i class="fa fa-heart-o fa-5x"></i>
      </li>
    
    </ul>
    <span class="top-prev"><i class="fa fa-2x fa-backward"></i></span>
    <span class="top-next"><i class="fa fa-2x fa-forward"></i></span>
  </div>
<script type="text/javascript">
  $(document).ready(function() {
  $("#container").jCarouselLite({　　
    btnNext: ".top-next",
    btnPrev: ".top-prev",
    scroll: 1,
    visible: 1,
    auto: 500,
    speed: 500, 
    vertical: false
    });
 
  });
</script>

<link rel="stylesheet" type="text/css" href="/assets/demo3/demo3.css">

<div class="icon-list">
         <i class="fa fa-adjust"></i> fa-adjust 
    
       <i class="fa fa-anchor"></i> fa-anchor 
    
       <i class="fa fa-archive"></i> fa-archive 
    
       <i class="fa fa-arrows"></i> fa-arrows 
    
       <i class="fa fa-arrows-h"></i> fa-arrows-h 
    
       <i class="fa fa-arrows-v"></i> fa-arrows-v 
    
       <i class="fa fa-asterisk"></i> fa-asterisk 
    
       <i class="fa fa-automobile"></i> fa-automobile <span class="text-muted">(alias)</span> 
    
       <i class="fa fa-ban"></i> fa-ban 
    
       <i class="fa fa-bank"></i> fa-bank <span class="text-muted">(alias)</span> 
    
       <i class="fa fa-bar-chart-o"></i> fa-bar-chart-o 
    
       <i class="fa fa-barcode"></i> fa-barcode 
    
    <i class="fa fa-bars"></i> fa-bars 
    
    <i class="fa fa-beer"></i> fa-beer 
    
    <i class="fa fa-bell"></i> fa-bell 
    
      <i class="fa fa-bell-o"></i> fa-bell-o 
    
    <i class="fa fa-bolt"></i> fa-bolt 
    
 <i class="fa fa-bomb"></i> fa-bomb 
    
 <i class="fa fa-book"></i> fa-book 
    
     <i class="fa fa-bookmark"></i> fa-bookmark 
    
       <i class="fa fa-bookmark-o"></i> fa-bookmark-o 
    
      <i class="fa fa-briefcase"></i> fa-briefcase 
    
<i class="fa fa-bug"></i> fa-bug 
    
     <i class="fa fa-building"></i> fa-building 
    
       <i class="fa fa-building-o"></i> fa-building-o 
    
     <i class="fa fa-bullhorn"></i> fa-bullhorn 
    
     <i class="fa fa-bullseye"></i> fa-bullseye 
    
 <i class="fa fa-cab"></i> fa-cab <span class="text-muted">(alias)</span> 
    
     <i class="fa fa-calendar"></i> fa-calendar 
    
       <i class="fa fa-calendar-o"></i> fa-calendar-o 
    
       <i class="fa fa-camera"></i> fa-camera 
    
      <i class="fa fa-camera-retro"></i> fa-camera-retro 
    
      <i class="fa fa-car"></i> fa-car 
    
       <i class="fa fa-caret-square-o-down"></i> fa-caret-square-o-down 
    
       <i class="fa fa-caret-square-o-left"></i> fa-caret-square-o-left 
    
       <i class="fa fa-caret-square-o-right"></i> fa-caret-square-o-right 
    
       <i class="fa fa-caret-square-o-up"></i> fa-caret-square-o-up 
    
      <i class="fa fa-certificate"></i> fa-certificate 
    
     <i class="fa fa-check"></i> fa-check 
    
      <i class="fa fa-check-circle"></i> fa-check-circle 
    
      <i class="fa fa-check-circle-o"></i> fa-check-circle-o 
    
      <i class="fa fa-check-square"></i> fa-check-square 
    
       <i class="fa fa-check-square-o"></i> fa-check-square-o 
    
       <i class="fa fa-child"></i> fa-child 
    
       <i class="fa fa-circle"></i> fa-circle 
    
       <i class="fa fa-circle-o"></i> fa-circle-o 
    
      <i class="fa fa-circle-o-notch"></i> fa-circle-o-notch 
    
       <i class="fa fa-circle-thin"></i> fa-circle-thin 
    
       <i class="fa fa-clock-o"></i> fa-clock-o 
    
       <i class="fa fa-cloud"></i> fa-cloud 
    
       <i class="fa fa-cloud-download"></i> fa-cloud-download 
    
       <i class="fa fa-cloud-upload"></i> fa-cloud-upload 
    
      <i class="fa fa-code"></i> fa-code 
    
       <i class="fa fa-code-fork"></i> fa-code-fork 
    
       <i class="fa fa-coffee"></i> fa-coffee 
    
      <i class="fa fa-cog"></i> fa-cog 
    
       <i class="fa fa-cogs"></i> fa-cogs 
    
      <i class="fa fa-comment"></i> fa-comment 
    
      <i class="fa fa-comment-o"></i> fa-comment-o 
    
      <i class="fa fa-comments"></i> fa-comments 
    
       <i class="fa fa-comments-o"></i> fa-comments-o 
    
       <i class="fa fa-compass"></i> fa-compass 
    
       <i class="fa fa-credit-card"></i> fa-credit-card 
    
       <i class="fa fa-crop"></i> fa-crop 
    
       <i class="fa fa-crosshairs"></i> fa-crosshairs 
    
      <i class="fa fa-cube"></i> fa-cube 
    
       <i class="fa fa-cubes"></i> fa-cubes 
    
       <i class="fa fa-cutlery"></i> fa-cutlery 
    
       <i class="fa fa-dashboard"></i> fa-dashboard <span class="text-muted">(alias)</span> 
    
       <i class="fa fa-database"></i> fa-database 
    
       <i class="fa fa-desktop"></i> fa-desktop 
    
       <i class="fa fa-dot-circle-o"></i> fa-dot-circle-o 
    
       <i class="fa fa-download"></i> fa-download 
    
       <i class="fa fa-edit"></i> fa-edit <span class="text-muted">(alias)</span> 
    
       <i class="fa fa-ellipsis-h"></i> fa-ellipsis-h 
    
       <i class="fa fa-ellipsis-v"></i> fa-ellipsis-v 
    
  <i class="fa fa-envelope"></i> fa-envelope 
    
    <i class="fa fa-envelope-o"></i> fa-envelope-o 
    
       <i class="fa fa-envelope-square"></i> fa-envelope-square 
    
<i class="fa fa-eraser"></i> fa-eraser 
    
  <i class="fa fa-exchange"></i> fa-exchange 
    
     <i class="fa fa-exclamation"></i> fa-exclamation 
    
      <i class="fa fa-exclamation-circle"></i> fa-exclamation-circle 
    
<i class="fa fa-exclamation-triangle"></i> fa-exclamation-triangle 
    
<i class="fa fa-external-link"></i> fa-external-link 
    
<i class="fa fa-external-link-square"></i> fa-external-link-square 
    
<i class="fa fa-eye"></i> fa-eye 
    
<i class="fa fa-eye-slash"></i> fa-eye-slash 
    
<i class="fa fa-fax"></i>
</div>

<a href="http://fontawesome.io/">fontawesome官网</a>